# Generated by Django 6.0.7 on 2026-07-25 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProviderMachine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('cpu_usage_percent', models.FloatField(default=0.0)),
                ('memory_total_gb', models.FloatField(default=0.0)),
                ('memory_used_gb', models.FloatField(default=0.0)),
                ('memory_usage_percent', models.FloatField(default=0.0)),
                ('disk_total_gb', models.FloatField(default=0.0)),
                ('disk_used_gb', models.FloatField(default=0.0)),
                ('disk_usage_percent', models.FloatField(default=0.0)),
                ('os_name', models.CharField(blank=True, max_length=50)),
                ('os_version', models.CharField(blank=True, max_length=100)),
                ('is_online', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='machines', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderHeartbeatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('cpu_usage_percent', models.FloatField()),
                ('memory_used_gb', models.FloatField()),
                ('memory_usage_percent', models.FloatField()),
                ('disk_used_gb', models.FloatField()),
                ('disk_usage_percent', models.FloatField()),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='providers.providermachine')),
            ],
        ),
    ]
