# Generated by Django 6.0.7 on 2026-07-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('providers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providermachine',
            name='cpu_count',
            field=models.IntegerField(default=1),
        ),
    ]
