# Generated by Django 6.0.7 on 2026-07-25 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('providers', '0002_providermachine_cpu_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RentalSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docker_image', models.CharField(max_length=255)),
                ('command', models.TextField(blank=True, null=True)),
                ('cpu_limit', models.FloatField()),
                ('memory_limit_mb', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped')], default='pending', max_length=20)),
                ('container_id', models.CharField(blank=True, max_length=128, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider_machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rentals', to='providers.providermachine')),
                ('renter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
