# Generated by Django 6.0.7 on 2026-07-25 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentalsession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('provisioning', 'Provisioning'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('stopped', 'Stopped'), ('stopping', 'Stopping')], default='pending', max_length=20),
        ),
    ]
