# Generated by Django 6.0.7 on 2026-07-25 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rentals', '0002_alter_rentalsession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalsession',
            name='error_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
